### ISSUE TITLE
BUG: WFTReviewPageLoad fires only on NEW nominations

### ISSUE THREAD

**Issue by AlterTobi** [MrJPGames/WayFarer-Toolkit#1]
WFTReviewPageLoad is only triggered, when window.wft.reviewApp.pageData.type === 'NEW'.
On PHOTO reviews and EDITs this Event is not called.

**Comment by MrJPGames** [comment]
With commits 2af72f2f0b876bd48f99d04f4b5d0aa306d566da and 5e25df2f1acb0b9186510b1c17a20de05e77e38f Wayfarer Toolkit will use the WFTReviewPageLoad as a generic review page load event. And now includes 3 new events: WFTNewReviewPageLoad, WFTEditReviewPageLoad and WFTPhotoReviewPageLoad.

Documentation will be updated when WF Toolkit version 0.4 is "ready".
